---
- name: Playbook reacting to AlertManager Event
  hosts: all
  connection: local
  gather_facts: false
  tasks:
    - name: Scale app
      when: ansible_eda.event.alert.status == "firing"
      kubernetes.core.k8s_scale:
        api_version: v1
        kind: Deployment
        name: quarkus-monitor
        namespace: default
        replicas: 2
        wait_timeout: 60
