---
- name: Listen for events from AlertManager
  hosts: all

  sources:
    - name: listen for alerts
      ansible.eda.alertmanager:
        host: 0.0.0.0
        port: 5001
        data_host_path: ""
  
  rules:
    - name: Scale Application
      condition: event.meta is defined
      actions:
        - print_event:
            pretty: true
        - run_playbook:
            name: playbook.yml