---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ansible-eda
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ansible-eda
  namespace: default
rules:
  - apiGroups: ["apps"]
    resources: ["pods", "deployments", "services", "jobs"]
    verbs: ["list", "get", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ansible-eda
  namespace: default
roleRef:
  kind: Role
  name: ansible-eda
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: ansible-eda
    namespace: default
---
apiVersion: batch/v1
kind: Job
metadata:
  name: ansible-eda-job
spec:
  template:
    spec:
      containers:
      - name: ansible-eda-job
        image: quay.io/rhdevelopers/ansible-eda:1.0.0
        #command: ["cowsay","Hello DevNation"]
      restartPolicy: Never
      serviceAccountName: ansible-eda